### ISSUE TITLE
UNC Package Destination Folderpath - Error

### ISSUE THREAD

**Issue by Pacomesy** [allenh-ni/nipm-api-labview#4]
I am using a feed located on a share with UNC notation (e.g. \\servername\folder\...).

When the application **NIPM Feed Manager** is started, it reads the file Feeds.ini.
Here is the problem:
The first **Read String.vi** has the Boolean **read raw string?** set to true and the second one not.

This result in a wrong interpretation of the server name (\servername instead of \\\\servername).

I set the Boolean **read raw string** to true for the second **Read String.vi** and everything is ok.

Have a nice day.
Christophe

**Comment by allenh-ni** [comment]
Fixed issue in [NIPM Feed Manager v2.3.0.17](https://github.com/allenh-ni/nipm-feed-manager-gui-labview/blob/master/Exports/national_instruments_lib_nipm_feed_manager_(beta)-2.3.0.17.vip)
Fixed bug in the Read Feed INI subVI, as described in this issue.
